### ISSUE TITLE
Configure GitHub Actions to Apply Supabase Migrations Automatically

### ISSUE THREAD

**Issue by m0nq** [m0nq/cloud-people#134]
We need to configure GitHub Actions to automatically apply database migration files from the `supabase/migrations` folder to our connected Supabase project whenever changes are pushed to the `main` branch. This will ensure that our cloud Supabase environment stays in sync with our codebase and avoids manual deployment steps.

## **Acceptance Criteria**

1. A GitHub Actions workflow is created or updated in the repository.
2. The workflow triggers on:
   * Push events to the `main` branch.
   * Pull request merges into `main`.
3. The workflow includes the following steps:
   * Install the Supabase CLI.
   * Authenticate with Supabase using an API key or service role key.
   * Run `supabase db push` to apply migrations from the `supabase/migrations` folder.
4. The workflow is tested and confirmed to successfully apply migrations in our connected Supabase project.

## **Technical Details**

* **Supabase CLI Installation**: Use the official [Supabase CLI](https://supabase.com/docs/guides/cli) for managing migrations.
* **Authentication**: Use a secure environment variable (e.g., `SUPABASE_ACCESS_TOKEN`) stored in GitHub Secrets for authenticating with Supabase.
* **GitHub Workflow File Location**: Place the workflow file in `.github/workflows/supabase-migrations.yml`.

## **Proposed Workflow YAML**

```
name: Apply Supabase Migrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  apply-migrations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install --global supabase

      - name: Authenticate with Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          echo $SUPABASE_ACCESS_TOKEN | supabase login --token

      - name: Apply Database Migrations
        run: supabase db push
```

## **Dependencies**

1. Ensure that a valid API key is present as a GitHub Secret (`SUPABASE_ACCESS_TOKEN`).
2. Ensure that all migration files are up-to-date and committed in the `supabase/migrations` folder.

## **Additional Notes**

* This workflow will only apply migrations; it does not handle rollback scenarios. If rollback functionality is required, a separate issue should be created.
* Notify the team once this feature is live so they can test it during their next migration update.
