### ISSUE TITLE
Implement Rollback Capability for Supabase Migrations in GitHub Actions

### ISSUE THREAD

**Issue by m0nq** [m0nq/cloud-people#135]
We need to enhance our existing GitHub Actions workflow to include the ability to rollback Supabase migrations. This feature will provide a safety net for our database changes, allowing us to revert to a previous state if issues arise after applying migrations.

## **Acceptance Criteria**

1. Update the existing GitHub Actions workflow to include rollback functionality.
2. Implement a mechanism to trigger rollbacks manually.
3. Create a separate workflow for rollbacks that can be triggered on-demand.
4. Ensure the rollback process is logged for auditing purposes.
5. Test the rollback functionality in a staging environment before implementing in production.

## **Technical Details**

* Use Supabase CLI's `db reset` command for rollbacks.
* Implement a way to specify the migration version to roll back to.
* Consider using GitHub environment variables to manage different environments (staging, production).

## **Proposed Workflow Updates**

1. Update the existing workflow to include a rollback step (conditionally executed):

```
name: Supabase Migrations

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Rollback to version (leave empty for no rollback)'
        required: false

jobs:
  database-changes:
    runs-on: ubuntu-latest

    steps:
      # ... [existing steps]

      - name: Apply Migrations or Rollback
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          if [ -n "${{ github.event.inputs.rollback }}" ]; then
            echo "Rolling back to version ${{ github.event.inputs.rollback }}"
            supabase db reset --db-url "$SUPABASE_DB_URL" --version "${{ github.event.inputs.rollback }}"
          else
            echo "Applying migrations"
            supabase db push
          fi

      - name: Log Database Changes
        run: |
          echo "Database changes applied/rolled back at $(date)" >> database_change_log.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add database_change_log.txt
          git commit -m "Update database change log"
          git push
```

2. Create a new workflow file for manual rollbacks:

```
name: Manual Supabase Rollback

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to rollback to'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: npm install -g supabase

      - name: Authenticate with Supabase
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: echo $SUPABASE_ACCESS_TOKEN | supabase login --token

      - name: Perform Rollback
        env:
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          supabase db reset --db-url "$SUPABASE_DB_URL" --version "${{ github.event.inputs.version }}"

      - name: Log Rollback
        run: |
          echo "Database rolled back to version ${{ github.event.inputs.version }} at $(date)" >> database_rollback_log.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add database_rollback_log.txt
          git commit -m "Log database rollback"
          git push
```

## **Dependencies**

1. Existing GitHub Actions workflow for applying migrations.
2. Supabase CLI installed in the workflow environment.
3. Proper Supabase authentication credentials stored as GitHub Secrets.

## **Additional Notes**

* Update documentation to include information about the rollback process.

* Consider implementing a notification system (e.g., Slack integration) to alert the team when a rollback occurs.

## **Risks and Mitigations**

* **Risk**: Accidental rollback in production.<br>**Mitigation**: Implement confirmation steps and restrict access to rollback triggers.
* **Risk**: Data loss during rollback.<br>**Mitigation**: Ensure proper backups are in place before allowing rollbacks.
